import html
import os
from pathlib import Path
import requests
import streamlit as st
from formatters.common import safe_filename, sanitize_text
from formatters.docx_formatter import format_docx
from formatters.pdf_formatter import format_pdf
from formatters.text_formatter import format_txt

BACKEND_URL = os.getenv("BACKEND_URL", "http://127.0.0.1:8000").rstrip("/")
st.set_page_config(page_title="LegalEase", page_icon="⚖️", layout="wide")
st.markdown("""<style>
.block-container { max-width:1200px; padding-top:2rem; }
.hero { text-align:center; padding:1rem 0 1.5rem; }
.legal-card { background:#111827; color:#f9fafb; padding:1.5rem; border-radius:14px; max-height:600px; overflow-y:auto; white-space:pre-wrap; font-family:Georgia,serif; line-height:1.65; }
</style>""", unsafe_allow_html=True)
st.markdown('<div class="hero"><h1>⚖️ LegalEase</h1><p>AI-Powered Legal Document Generator</p></div>', unsafe_allow_html=True)
st.info("LegalEase creates document drafts for informational and preparation purposes. Review generated text with a qualified legal professional before relying on it.")

with st.sidebar:
    st.header("Document settings")
    document_type = st.selectbox("Document type", ["Employment Contract", "Non-Disclosure Agreement (NDA)", "Lease Agreement", "Employment Offer Letter", "Freelance Work Contract", "Service Agreement", "General Agreement", "Custom"])
    if document_type == "Custom": document_type = st.text_input("Custom document type", "Custom Legal Agreement")
    language = st.selectbox("Language", ["English", "Tamil", "Hindi", "Telugu", "Kannada", "Malayalam"])
    effective_date = st.text_input("Effective date", "September 26, 2026")
    company_name = st.text_input("Brand/company name", "LegalEase")

st.subheader("1. Parties")
parties = st.text_area("Who are the parties?", placeholder="Jane Doe (Service Provider), TechNova Inc. (Client)", height=110)
st.subheader("2. Terms & Conditions")
terms_raw = st.text_area("Enter one term per line or separate terms with semicolons", placeholder="Payment to be made within 30 days of invoice; Confidentiality must be maintained; Either party may terminate with 15 days notice", height=150)
terms = [x.strip() for x in terms_raw.replace(";", "\n").splitlines() if x.strip()]
st.subheader("3. Additional instructions")
additional_instructions = st.text_area("Optional drafting instructions", placeholder="Use a formal tone. Include signature blocks. Avoid inventing missing facts.", height=100)

if "document" not in st.session_state: st.session_state.document = ""
if st.button("✨ Generate Document", type="primary", use_container_width=True):
    if not parties.strip(): st.error("Please enter the parties involved.")
    elif not effective_date.strip(): st.error("Please enter an effective date.")
    else:
        payload = {"document_type": document_type, "parties": parties, "terms": terms, "effective_date": effective_date, "language": language, "additional_instructions": additional_instructions}
        try:
            with st.spinner("Generating your legal draft..."):
                response = requests.post(f"{BACKEND_URL}/generate", json=payload, timeout=120)
            if response.ok:
                data = response.json(); st.session_state.document = data["content"]; st.session_state.generated_model = data.get("model", ""); st.success("Document generated.")
            else:
                try: detail = response.json().get("detail", response.text)
                except ValueError: detail = response.text
                st.error(f"Backend error: {detail}")
        except requests.RequestException as exc:
            st.error(f"Could not connect to FastAPI at {BACKEND_URL}. Start the backend first. Details: {exc}")

if st.session_state.document:
    st.divider(); st.subheader("4. Preview & Edit")
    st.caption(f"Generated by {st.session_state.get('generated_model', 'Gemini')}. Edit the draft before exporting.")
    edited = st.text_area("Editable document", value=st.session_state.document, height=500, label_visibility="collapsed")
    st.session_state.document = edited
    st.markdown(f'<div class="legal-card">{html.escape(sanitize_text(edited))}</div>', unsafe_allow_html=True)
    st.subheader("5. Download")
    filename = safe_filename(document_type)
    c1, c2, c3 = st.columns(3)
    with c1: st.download_button("⬇️ Download TXT", data=format_txt(edited), file_name=f"{filename}.txt", mime="text/plain", use_container_width=True)
    with c2: st.download_button("⬇️ Download DOCX", data=format_docx(edited, document_type, terms=terms, company_name=company_name), file_name=f"{filename}.docx", mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document", use_container_width=True)
    with c3: st.download_button("⬇️ Download PDF", data=format_pdf(edited, document_type, terms=terms, company_name=company_name), file_name=f"{filename}.pdf", mime="application/pdf", use_container_width=True)

st.divider(); st.caption("LegalEase is an AI drafting tool. It is not a law firm and does not provide legal advice.")
